[package]
name = "libviprs-cli"
version = "0.1.0"
edition = "2024"
authors = ["Roman Goldmann <roman@devshell.org>"]
rust-version = "1.85"

[lints.rust]
deprecated = "deny"

[lints.clippy]
incompatible_msrv = "warn"

[[bin]]
name = "viprs"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
libviprs = { path = "../libviprs", features = ["pdfium"] }
